name: Deploy Laravel to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Copy .env
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Generate key
      - name: Generate Laravel key
        run: php artisan key:generate

      # Set permissions
      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      # Deploy to Render via GitHub Action
      - name: Deploy to Render
        uses: render-examples/deploy-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
